### ISSUE TITLE
เรียกใช้กับ field อื่นได้มั้ย?

### ISSUE THREAD

**Issue by mennwebs** [SeedThemes/seed-buddhist-year#1]
มีคนถามที่ https://th.seedthemes.com/topic/7305/#post-7327

ถ้าเราต้องการ ไปใส่ code เขียน เพิ่มใน single.php แสดง วันที่วันนี้ ผมลองใช้
<?php echo date_i18n(‘j F Y’) ?> กับ <?php echo date(‘j F Y’) ?> มันไม่เปลี่ยนยังเป็น 2016

และถ้าเราจะให้แสดงวันที่ที่เรา custom field เองต้องเขียน format ยังไงครับ
ถ้า code ที่ดึงเป็นแบบนี้ <?php echo $birthday ?>
ซึ่งลองลง plugin แล้วมันเป็น 2016 ไม่เปลี่ยน
เปลี่ยนแต่วันที่เรา post ไปเท่านั้นครับ

**Comment by vaivaisoft** [comment]
อันนี้คือส่วนที่เคยบอกพี่ไปไง ว่าถ้าต้องการไปดักทุกๆ function ของ Wordpress เลยมันต้องไปทำ function อื่นด้วยนะ ไม่ใช่แค่ชุด the_date() get_the_date() the_time() get_the_time() แค่ 4 ตัว

และฟังก์ชันที่ทำได้ ก้จะมีแค่ฟังกืชันเวิร์ดเพรซด้วยนะ จะเป็นฟังก์ชันของ PHP ไม่ได้เลย อย่างที่เค้ายกตัวอย่างมา ก็จะได้แค่ date_i18n แต่ date จะไม่ได้

**Comment by mennwebs** [comment]
ใช่ๆ ไม่ได้ไปทำให้ แต่คำถามคือ เรามีฟังก์ชันให้เรียกใช้ด้วยหรือเปล่า เช่น

seed_buddhist_year($exampledate)

แล้วมัน return ค่าเป็น พ.ศ. มาให้น่ะ

หรือถ้าไม่มี แนะนำวิธเขียนฟ้งก์ชั่นนี้ได้มั้ย

**Comment by vaivaisoft** [comment]
งั้นเพิ่มฟังก์ชัน seed_buddhist_year ไปแล้ว push ไปแล้ว

ลองใช้ดู ถ้าเอาวันที่ปัจจุบัน จะใช้ <?php echo seed_buddhist_year(); ?> ได้เลย คือใช้มันแทน date_i18n() ได้เลย attributes เหมือนกันทุกอย่าง
