### ISSUE TITLE
วันที่คอมเม้นต์และใน bbpress ยังไม่รองรับ

### ISSUE THREAD

**Issue by mennwebs** [SeedThemes/seed-buddhist-year#5]
อยากให้ช่วยเช็ควันที่ในคอมเม้นท์ กับใน BBPress ให้หน่อยว่ามีทางทำให้รองรับตัวนี้ได้หรือเปล่า

**Comment by vaivaisoft** [comment]
ตอนนี้วันที่ในคอมเมนต์ใช้ได้แล้วนะครับ
